name: 'Setup Node.js and Dependencies'
description: 'Setup Node.js with npm cache and install dependencies'

inputs:
  node-version:
    description: 'Node.js version to setup'
    required: false
    default: '20'
  cache:
    description: 'Cache npm dependencies'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache == 'true' && 'npm' || '' }}

    - name: Install dependencies
      run: npm ci
      shell: bash
